<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <RootNamespace>AudioBatchConverter.Worker</RootNamespace>
    <AssemblyName>AudioBatchConverter.Worker</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AudioBatchConverter.Core\AudioBatchConverter.Core.csproj" />
  </ItemGroup>
</Project>
